/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace ArcSafeTradeEscrow {
      
    export type TradeStruct = {buyer: AddressLike, seller: AddressLike, amount: BigNumberish, status: BigNumberish, createdAt: BigNumberish, fundedAt: BigNumberish, shippedAt: BigNumberish, completedAt: BigNumberish}

    export type TradeStructOutput = [buyer: string, seller: string, amount: bigint, status: bigint, createdAt: bigint, fundedAt: bigint, shippedAt: bigint, completedAt: bigint] & {buyer: string, seller: string, amount: bigint, status: bigint, createdAt: bigint, fundedAt: bigint, shippedAt: bigint, completedAt: bigint }
  
    }

  export interface ArcSafeTradeEscrowInterface extends Interface {
    getFunction(nameOrSignature: "cancelBeforeFunding" | "confirmReceived" | "createTrade" | "fundTrade" | "getTrade" | "markShipped" | "nextTradeId" | "openDispute" | "owner" | "renounceOwnership" | "resolveDispute" | "trades" | "transferOwnership" | "usdc"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeResolved" | "OwnershipTransferred" | "TradeCancelled" | "TradeCompleted" | "TradeCreated" | "TradeDisputed" | "TradeFunded" | "TradeRefunded" | "TradeShipped"): EventFragment;

    encodeFunctionData(functionFragment: 'cancelBeforeFunding', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'confirmReceived', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createTrade', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fundTrade', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTrade', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'markShipped', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'nextTradeId', values?: undefined): string;
encodeFunctionData(functionFragment: 'openDispute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, boolean]): string;
encodeFunctionData(functionFragment: 'trades', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'cancelBeforeFunding', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'confirmReceived', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createTrade', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fundTrade', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTrade', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'markShipped', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextTradeId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'openDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'trades', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
  }

  
    export namespace DisputeResolvedEvent {
      export type InputTuple = [tradeId: BigNumberish, releasedToSeller: boolean];
      export type OutputTuple = [tradeId: bigint, releasedToSeller: boolean];
      export interface OutputObject {tradeId: bigint, releasedToSeller: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeCancelledEvent {
      export type InputTuple = [tradeId: BigNumberish];
      export type OutputTuple = [tradeId: bigint];
      export interface OutputObject {tradeId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeCompletedEvent {
      export type InputTuple = [tradeId: BigNumberish, seller: AddressLike, amount: BigNumberish];
      export type OutputTuple = [tradeId: bigint, seller: string, amount: bigint];
      export interface OutputObject {tradeId: bigint, seller: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeCreatedEvent {
      export type InputTuple = [tradeId: BigNumberish, buyer: AddressLike, seller: AddressLike, amount: BigNumberish];
      export type OutputTuple = [tradeId: bigint, buyer: string, seller: string, amount: bigint];
      export interface OutputObject {tradeId: bigint, buyer: string, seller: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeDisputedEvent {
      export type InputTuple = [tradeId: BigNumberish, openedBy: AddressLike];
      export type OutputTuple = [tradeId: bigint, openedBy: string];
      export interface OutputObject {tradeId: bigint, openedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeFundedEvent {
      export type InputTuple = [tradeId: BigNumberish, buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [tradeId: bigint, buyer: string, amount: bigint];
      export interface OutputObject {tradeId: bigint, buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeRefundedEvent {
      export type InputTuple = [tradeId: BigNumberish, buyer: AddressLike, amount: BigNumberish];
      export type OutputTuple = [tradeId: bigint, buyer: string, amount: bigint];
      export interface OutputObject {tradeId: bigint, buyer: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TradeShippedEvent {
      export type InputTuple = [tradeId: BigNumberish, seller: AddressLike];
      export type OutputTuple = [tradeId: bigint, seller: string];
      export interface OutputObject {tradeId: bigint, seller: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ArcSafeTradeEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): ArcSafeTradeEscrow;
    waitForDeployment(): Promise<this>;

    interface: ArcSafeTradeEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    cancelBeforeFunding: TypedContractMethod<
      [tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    confirmReceived: TypedContractMethod<
      [tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createTrade: TypedContractMethod<
      [seller: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    fundTrade: TypedContractMethod<
      [tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getTrade: TypedContractMethod<
      [tradeId: BigNumberish, ],
      [ArcSafeTradeEscrow.TradeStructOutput],
      'view'
    >
    

    
    markShipped: TypedContractMethod<
      [tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    nextTradeId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    openDispute: TypedContractMethod<
      [tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [tradeId: BigNumberish, releaseToSeller: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    trades: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, amount: bigint, status: bigint, createdAt: bigint, fundedAt: bigint, shippedAt: bigint, completedAt: bigint }],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'cancelBeforeFunding'): TypedContractMethod<
      [tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'confirmReceived'): TypedContractMethod<
      [tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createTrade'): TypedContractMethod<
      [seller: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fundTrade'): TypedContractMethod<
      [tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTrade'): TypedContractMethod<
      [tradeId: BigNumberish, ],
      [ArcSafeTradeEscrow.TradeStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'markShipped'): TypedContractMethod<
      [tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'nextTradeId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'openDispute'): TypedContractMethod<
      [tradeId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [tradeId: BigNumberish, releaseToSeller: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'trades'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, string, bigint, bigint, bigint, bigint, bigint, bigint] & {buyer: string, seller: string, amount: bigint, status: bigint, createdAt: bigint, fundedAt: bigint, shippedAt: bigint, completedAt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TradeCancelled'): TypedContractEvent<TradeCancelledEvent.InputTuple, TradeCancelledEvent.OutputTuple, TradeCancelledEvent.OutputObject>;
getEvent(key: 'TradeCompleted'): TypedContractEvent<TradeCompletedEvent.InputTuple, TradeCompletedEvent.OutputTuple, TradeCompletedEvent.OutputObject>;
getEvent(key: 'TradeCreated'): TypedContractEvent<TradeCreatedEvent.InputTuple, TradeCreatedEvent.OutputTuple, TradeCreatedEvent.OutputObject>;
getEvent(key: 'TradeDisputed'): TypedContractEvent<TradeDisputedEvent.InputTuple, TradeDisputedEvent.OutputTuple, TradeDisputedEvent.OutputObject>;
getEvent(key: 'TradeFunded'): TypedContractEvent<TradeFundedEvent.InputTuple, TradeFundedEvent.OutputTuple, TradeFundedEvent.OutputObject>;
getEvent(key: 'TradeRefunded'): TypedContractEvent<TradeRefundedEvent.InputTuple, TradeRefundedEvent.OutputTuple, TradeRefundedEvent.OutputObject>;
getEvent(key: 'TradeShipped'): TypedContractEvent<TradeShippedEvent.InputTuple, TradeShippedEvent.OutputTuple, TradeShippedEvent.OutputObject>;

    filters: {
      
      'DisputeResolved(uint256,bool)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TradeCancelled(uint256)': TypedContractEvent<TradeCancelledEvent.InputTuple, TradeCancelledEvent.OutputTuple, TradeCancelledEvent.OutputObject>;
      TradeCancelled: TypedContractEvent<TradeCancelledEvent.InputTuple, TradeCancelledEvent.OutputTuple, TradeCancelledEvent.OutputObject>;
    

      'TradeCompleted(uint256,address,uint256)': TypedContractEvent<TradeCompletedEvent.InputTuple, TradeCompletedEvent.OutputTuple, TradeCompletedEvent.OutputObject>;
      TradeCompleted: TypedContractEvent<TradeCompletedEvent.InputTuple, TradeCompletedEvent.OutputTuple, TradeCompletedEvent.OutputObject>;
    

      'TradeCreated(uint256,address,address,uint256)': TypedContractEvent<TradeCreatedEvent.InputTuple, TradeCreatedEvent.OutputTuple, TradeCreatedEvent.OutputObject>;
      TradeCreated: TypedContractEvent<TradeCreatedEvent.InputTuple, TradeCreatedEvent.OutputTuple, TradeCreatedEvent.OutputObject>;
    

      'TradeDisputed(uint256,address)': TypedContractEvent<TradeDisputedEvent.InputTuple, TradeDisputedEvent.OutputTuple, TradeDisputedEvent.OutputObject>;
      TradeDisputed: TypedContractEvent<TradeDisputedEvent.InputTuple, TradeDisputedEvent.OutputTuple, TradeDisputedEvent.OutputObject>;
    

      'TradeFunded(uint256,address,uint256)': TypedContractEvent<TradeFundedEvent.InputTuple, TradeFundedEvent.OutputTuple, TradeFundedEvent.OutputObject>;
      TradeFunded: TypedContractEvent<TradeFundedEvent.InputTuple, TradeFundedEvent.OutputTuple, TradeFundedEvent.OutputObject>;
    

      'TradeRefunded(uint256,address,uint256)': TypedContractEvent<TradeRefundedEvent.InputTuple, TradeRefundedEvent.OutputTuple, TradeRefundedEvent.OutputObject>;
      TradeRefunded: TypedContractEvent<TradeRefundedEvent.InputTuple, TradeRefundedEvent.OutputTuple, TradeRefundedEvent.OutputObject>;
    

      'TradeShipped(uint256,address)': TypedContractEvent<TradeShippedEvent.InputTuple, TradeShippedEvent.OutputTuple, TradeShippedEvent.OutputObject>;
      TradeShipped: TypedContractEvent<TradeShippedEvent.InputTuple, TradeShippedEvent.OutputTuple, TradeShippedEvent.OutputObject>;
    
    };
  }